data:
  train_data: 'train.csv'
  test_data: 'test.csv'
  data_path: './data/'
  output_path: './output/'

# 사용하지 않을 모델, 평가지표, 컬럼은 주석처리
models:
  # baseline or tuning mode 존재
  mode: 'tuning'
  active_model:
    - 'lr'
    - 'ridge'
    - 'dt'
    - 'rf'
    - 'et'
    - 'xgb'
    - 'lgbm'
    - 'cat'
  trial : 2 # tuning 모드일 경우 반복 횟수
  save_path: './models/'

metrics:
  - 'MAE'
  - 'RMSE'
  - 'NMAE'
  - 'R2'

seed: 41

target: 'TARGET'

feature:
  - 'sessionID'
  - 'userID'
  - 'browser'
  - 'OS'
  - 'device'
  - 'new'
  - 'quality'
  - 'duration'
  - 'bounced'
  - 'transaction'
  - 'transaction_revenue'
  - 'continent'
  - 'subcontinent'
  - 'country'
  - 'traffic_source'
  - 'traffic_medium'

# mean, median 중 1개 선택
fill_method:
  method: 'median'

# standard, minmax, robust, iqr, none 중 1개 선택
scale:
  scale_target: 
    - 'transaction_revenue'
  scale_method: 'standard'